# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesseractForCSV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesseractForCSV
  pod 'TesseractOCRiOS'

  target 'TesseractForCSVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesseractForCSVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
